### ISSUE TITLE
invalid-decorator-type for custom types

### ISSUE THREAD

**Issue by eddingston** [borremosch/eslint-plugin-type-graphql#15]
Hello,

According to the https://github.com/borremosch/eslint-plugin-type-graphql/blob/main/docs/rules/invalid-decorator-type.md, it looks like `Type functions must specify a TypeGraphQL literal or TypeScript type`. Should I just disable this rule so we can use custom types? Or am I doing something wrong here?

When I disable the invalid-decorator-type it seems that it also affects the checking of the nullable fields on fields with custom types.

Thank you for your time!

**Comment by borremosch** [comment]
There is support for custom types in the [wrong-decorator-signature](https://github.com/borremosch/eslint-plugin-type-graphql/blob/main/docs/rules/wrong-decorator-signature.md) rule. This is the error that would trigger when you use custom types without additional configuration.

The invalid-decorator-type rule should apply only to types that are invalid by TypeGraphQLs design. It should not affect nullability checking.

If you are still experiencing problems, consider adding a code example so I can be of more help.
