### ISSUE TITLE
Error using GraphQLJSON

### ISSUE THREAD

**Issue by devotox** [borremosch/eslint-plugin-type-graphql#16]
Code

```
  @Field(() => GraphQLJSON, { nullable: true })
  public icon?: Record<any, any>
```

Error: 
`Decorator type does not match corresponding TypeScript type. Expected () => __type but found () => GraphQLJSON`

GraphQLJSON type comes from: https://github.com/taion/graphql-type-json

**Comment by rchl** [comment]
That rule supports custom mappings. See https://github.com/borremosch/eslint-plugin-type-graphql/blob/main/docs/rules/wrong-decorator-signature.md#options

Not sure how the mapping key for the `Record<any, any>` would look like though. Might have to log `decoratedType.name` in the rule here https://github.com/borremosch/eslint-plugin-type-graphql/blob/aff589cef806b3728f311410325805a854c3d80b/src/rules/wrong-decorator-signature.ts#L127

**Comment by borremosch** [comment]
@rchl is right. However, I might add that the linter is not very valuable in cases where you are not using strict type checking (for example when using `any`). You might as well ignore the error completely:

```js
// eslint-disable-next-line type-graphql/wrong-decorator-signature
@Field(() => GraphQLJSON, { nullable: true })
public icon?: Record<any, any>
```
