### ISSUE TITLE
is "recommended-requiring-type-checking" required to use this eslint plugin?

### ISSUE THREAD

**Issue by AndysonDK** [borremosch/eslint-plugin-type-graphql#19]
Even though it's specified in the recommended configuration of `eslint-plugin-type-graphql` that you should use `plugin:@typescript-eslint/recommended-requiring-type-checking`. Can i still use this plugin without it? Because `plugin:@typescript-eslint/recommended-requiring-type-checking` slows down the VS Code ESLint extension too much IMO. Also do you have any good ideas to make the VS Code ESLint extension run faster with the `recommended-requiring-type-checking` rules enabled?

**Comment by borremosch** [comment]
@AndysonDK enabling the recommended type checking rules should not be required, as long as the Typescript parser is enabled.
