### ISSUE TITLE
Custom field type and "wrong-decorator-signature" rule

### ISSUE THREAD

**Issue by rchl** [borremosch/eslint-plugin-type-graphql#5]
For code like this:

```ts
import BigIntType from 'apollo-type-bigint';

const BigInt = new BigIntType('safe');

@ObjectType()
export class Album {
    @Field(() => BigInt)
    public id: number = 0;
}
```

I'm getting those errors:
```
Type number trivially inferred from a number literal, remove type annotation.
Decorator type does not match corresponding TypeScript type. Expected () => Int, ,() => Float, or () => ID but found () => BigInt.
```

Both seem unwanted in this case but the main issue is with `Decorator type does not match corresponding TypeScript type` I guess. I believe that I can't use `BigInt` type at runtime since it's a graphql type to be used with graphql only. Typescript would not allow assigning a literal number to a property typed with `BigInt`.

Is there something I can do in this case apart from ignoring the error?

If there is no way to handle it in a generic way then I guess an option would be for the rule to accept some configuration that would define the expected mapping between the graphql and typescript types.

**Comment by borremosch** [comment]
Thanks for your feedback @rchl! I am considering two approaches here:

First, it might be a good idea to support ES native `bigint` and map it to `BigInt` inside a decorator. That should solve your problem, as long as you are able to support ES2020 and if you are using actual `bigint`s in your codebase (not `number`).

Even if this fixes your problem, there are probably other use cases where supporting ES2020 is not viable. In this case, perhaps the linter can be configured to allow certain custom mappings between TypeScript types and GraphQL types. You could then define yourself whether you want to allow decorating `bigint` with `BigInt`. This would be a very flexible solution that should work for a lot of other use cases as well.

I will take some time over the next couple of days to think about this

**Comment by rchl** [comment]
As can be seen on https://www.npmjs.com/package/apollo-type-bigint, the `apollo-type-bigint `BigInt` can be initialized with either "safe" (53-bit) or "bigInt" (63-bit) arguments. The "safe" version is equivalent to JS' `number` type which is also 53-bit while the 63-bit one is equivalent to native `BigInt`. So it makes perfect sense to use `BigInt("safe")` with `number` type on the typescript side -- it's only *Big* relative to GraphQL `Int`, not to JS'.

Since I'm on Node >10, I could use native BigInt but as explained above, I shouldn't need to.

I would say that it would make more sense to support providing custom mapping rather than including mapping for this one by default since "BigInt" on the graphql doesn't mean anything natively in GraphQL and the name of the type the user will create doesn't have to match `BigInt` exactly either.

**Comment by rchl** [comment]
That you for fixing this 👍
