### ISSUE TITLE
Wrong invalid-decorator-type rule

### ISSUE THREAD

**Issue by MichalLytek** [borremosch/eslint-plugin-type-graphql#6]
The docs says:

> Examples of correct code for this rule:
> ```ts
> @Field(() => Int, { nullable: 'items' })
> timestamps?: Array<number | null>;
> ```

However `type-graphql@1.0.0` had a breaking change: 
"remove legacy array inference - now explicit array syntax (`[Item]`) is required"

**Comment by borremosch** [comment]
Thank you for mentioning this, I had not noticed the change. I will publish a fix for this rule soon
